"""Application-facing browser automation port."""

from pathlib import Path
from typing import Protocol

from hermes_edu.domain.models.browser import (
    BrowserObservation,
    BrowserReadMode,
    BrowserSession,
    BrowserViewport,
    PageSnapshot,
)


class BrowserPort(Protocol):
    def create_session(self, *, headless: bool, viewport: BrowserViewport) -> BrowserSession: ...
    def get_session(self, session_id: str) -> BrowserSession: ...
    def open(self, session_id: str, url: str) -> BrowserObservation: ...
    def navigate(self, session_id: str, url: str) -> BrowserObservation: ...
    def read(self, session_id: str, *, mode: BrowserReadMode) -> BrowserObservation: ...
    def click(
        self, session_id: str, *, element_id: str = "", text: str = ""
    ) -> BrowserObservation: ...
    def type(self, session_id: str, element_id: str, text: str) -> BrowserObservation: ...
    def fill(self, session_id: str, element_id: str, text: str) -> BrowserObservation: ...
    def scroll(
        self,
        session_id: str,
        *,
        direction: str = "down",
        pixels: int = 800,
        element_id: str = "",
    ) -> BrowserObservation: ...
    def select(self, session_id: str, element_id: str, value: str) -> BrowserObservation: ...
    def check(
        self, session_id: str, element_id: str, *, checked: bool = True
    ) -> BrowserObservation: ...
    def press(self, session_id: str, key: str) -> BrowserObservation: ...
    def wait(
        self,
        session_id: str,
        *,
        element_id: str = "",
        text: str = "",
        timeout_ms: int = 5000,
    ) -> BrowserObservation: ...
    def screenshot(
        self,
        session_id: str,
        *,
        full_page: bool = False,
        element_id: str = "",
    ) -> BrowserObservation: ...
    def download(
        self,
        session_id: str,
        *,
        element_id: str = "",
        url: str = "",
    ) -> BrowserObservation: ...
    def back(self, session_id: str) -> BrowserObservation: ...
    def forward(self, session_id: str) -> BrowserObservation: ...
    def reload(self, session_id: str) -> BrowserObservation: ...
    def tabs(self, session_id: str) -> BrowserObservation: ...
    def switch_tab(self, session_id: str, tab_id: str) -> BrowserObservation: ...
    def close_tab(self, session_id: str, tab_id: str = "") -> BrowserObservation: ...
    def snapshot(self, session_id: str) -> PageSnapshot: ...
    def close(self, session_id: str) -> BrowserObservation: ...
    def shutdown(self) -> None: ...


class BrowserDownloadedReferencePort(Protocol):
    def import_pdf_bytes(
        self, content: bytes, filename: str, *, title: str | None = None
    ) -> str: ...


class DownloadReaderPort(Protocol):
    def read_download(self, path: Path) -> bytes: ...
