"""Boundaries used by reference-library use cases."""

from contextlib import AbstractContextManager
from pathlib import Path
from typing import Protocol

from hermes_edu.domain.models.reference import (
    MathChunk,
    ParsedReference,
    Reference,
    ReferenceFilters,
)


class ReferenceFilesPort(Protocol):
    def read(self, path: Path) -> bytes: ...
    def list_pdfs(self, directory: Path) -> tuple[Path, ...]: ...
    def retain(self, content_hash: str, content: bytes) -> None: ...
    def retained(self, content_hash: str) -> bytes: ...
    def remove(self, content_hash: str) -> None: ...


class ReferenceEventsPort(Protocol):
    def info(self, event: str, **fields: object) -> None: ...
    def warning(self, event: str, **fields: object) -> None: ...


class ReferenceParserPort(Protocol):
    @property
    def version(self) -> str: ...

    @property
    def ocr_version(self) -> str: ...

    def parse(self, content: bytes, document_id: str) -> ParsedReference: ...


class ReferenceChunkerPort(Protocol):
    @property
    def version(self) -> str: ...
    def chunk(self, parsed: ParsedReference, title: str) -> tuple[MathChunk, ...]: ...


class ReferenceRepositoryPort(Protocol):
    def transaction(self) -> AbstractContextManager[None]: ...
    def get_by_hash(self, content_hash: str) -> Reference | None: ...
    def get(self, document_id: str) -> Reference | None: ...
    def list(self) -> tuple[Reference, ...]: ...
    def save(self, reference: Reference) -> None: ...
    def parsed(self, document_id: str, fingerprint: str) -> ParsedReference | None: ...
    def save_parsed(self, parsed: ParsedReference, fingerprint: str) -> None: ...
    def chunks(self, document_id: str, fingerprint: str) -> tuple[MathChunk, ...]: ...
    def save_chunks(self, chunks: tuple[MathChunk, ...], fingerprint: str) -> None: ...
    def vector_labels(
        self, chunk_ids: tuple[str, ...], model: str, dimension: int, index_version: str
    ) -> dict[str, tuple[int, bool]]: ...
    def vector_dimension(
        self, chunk_ids: tuple[str, ...], model: str, index_version: str
    ) -> int: ...
    def allocate_labels(
        self, chunk_ids: tuple[str, ...], model: str, dimension: int, index_version: str
    ) -> dict[str, int]: ...
    def mark_indexed(self, labels: tuple[int, ...]) -> None: ...
    def eligible_labels(
        self, filters: ReferenceFilters, model: str, dimension: int, index_version: str
    ) -> tuple[int, ...]: ...
    def chunks_for_labels(self, labels: tuple[int, ...]) -> dict[int, tuple[MathChunk, str]]: ...
    def related_chunks(self, chunk_id: str) -> tuple[MathChunk, ...]: ...
    def all_labels(self, document_id: str) -> tuple[tuple[str, int, int, str], ...]: ...
    def prune_vectors(
        self,
        document_id: str,
        active_chunk_ids: tuple[str, ...],
        model: str,
        dimension: int,
        index_version: str,
    ) -> tuple[tuple[str, int, int, str], ...]: ...
    def remove(self, document_id: str) -> None: ...
    def count_active(self) -> int: ...


class ReferenceVectorPort(Protocol):
    def contains(self, model: str, dimension: int, index_version: str, label: int) -> bool: ...
    def contains_many(
        self, model: str, dimension: int, index_version: str, labels: tuple[int, ...]
    ) -> bool: ...
    def add(
        self,
        model: str,
        dimension: int,
        index_version: str,
        vectors: tuple[tuple[int, tuple[float, ...]], ...],
        *,
        replace_existing: bool = False,
    ) -> None: ...
    def search(
        self,
        model: str,
        dimension: int,
        index_version: str,
        query: tuple[float, ...],
        allowed_labels: tuple[int, ...],
        top_k: int,
    ) -> tuple[tuple[int, float], ...]: ...
    def remove(
        self, model: str, dimension: int, index_version: str, labels: tuple[int, ...]
    ) -> None: ...
